<?php $helper = Mage::helper('data_icrc/internal'); ?>
ICRC.unit_validator_data = <?php echo $helper->getRadarJson('unit') ?>;
ICRC.delegation_validator_data = <?php echo $helper->getRadarJson('delegation') ?>;
ICRC.unit_delegation_validator_data = <?php echo $helper->getRadarJson('unit-delegation') ?>;
ICRC.oc_validator_data = <?php echo $helper->getRadarJson('objective-code') ?>;
ICRC.cc_validator_data = <?php echo $helper->getRadarJson('cost-center') ?>;

