<div class="share dyn-block dyn-block-external" id="icrc-share-product-bar">
  <script type="text/javascript">
  //<![CDATA[
  document.observe("dom:loaded", function() {
    var script_tag = document.createElement('script');
    script_tag.type = "text/javascript";
    script_tag.src = "//s7.addthis.com/js/250/addthis_widget.js#username=xa-4cbee2246533f2f1";
    document.getElementsByTagName('head')[0].appendChild(script_tag);
  });
  //]]>
  </script>
  <!-- <script type="text/javascript" src="//s7.addthis.com/js/250/addthis_widget.js#username=xa-4cbee2246533f2f1"></script> -->
  <div class="addthis_toolbox addthis_default_style">
    <ul class="socilaTools" id="stools">
	    <a href="http://www.addthis.com/bookmark.php?v=250&amp;username=xa-4cbee2246533f2f1" class="addthis_button_compact"><?php echo $this->__('Share') ?></a>
	    <span class="addthis_separator">|</span>
	    <a class="addthis_button_preferred_1"></a>
	    <a class="addthis_button_preferred_5"></a>
	    <a class="addthis_button_preferred_3"></a>
	    <a class="addthis_button_preferred_10"></a>
    </ul>
  </div>
</div>
