<div class="checkout-title"><h2><?php echo $this->__('Validation Information') ?></h2></div>
<form action="" id="co-validation-form">
  <fieldset class="internal-checkout-form">
    <ul class="form-list">
      <li>
        <label for="validation-email" class="required"><em>*</em>Budget Manager e-mail to validate order</label>
        <div class="input-box">
          <input type="text" class="input-text required-entry validate-email" id="validation-email" name="validation[icrc_email]" value="" />
        </div>
      </li>
    </ul>
  </fieldset>
</form>
