<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
</div>
<div id="messages_product_view_language"></div>
<form action="<?php echo $this->getFormAction(); ?>" id="otherlanguageForm" method="post" onsubmit="return false;">
    <div class="fieldset">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"><?php echo $this->__('- Name of product: %s', $this->getProduct()->getName())."\n";
                        echo $this->__('- Reference: %s', $this->getProduct()->getSku())."\n";
                        echo $this->__('- Language of demand: %s', $this->getLang())."\n";
                        ?>
                    </textarea>
                </div>
                 <div class="icrc-requested-button-to-be-there">
                  <button id="submitlanguage" type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
                </div>
            </li>
            <?php echo $this->getChildHtml('captcha'); ?>
        </ul>
        <input type="hidden" name="lang" value="<?php echo $this->getLang() ?>"/>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var otherlanguageForm = new VarienForm('otherlanguageForm', true);
//]]>
</script>
